"""empty message

Revision ID: 8e2ecca5d7ba
Revises: None
Create Date: 2016-11-23 20:48:49.262529

"""

# revision identifiers, used by Alembic.
revision = '8e2ecca5d7ba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table')
    ### end Alembic commands ###
